# Cloudflare Pages 部署配置
name = "blog-v2"
compatibility_date = "2025-11-25"

[assets]
directory = "./dist"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[routes]]
pattern = "qinrenjihe.com"
custom_domain = true

[[routes]]
pattern = "bigroc.cn"
custom_domain = true

[[routes]]
pattern = "www.qinrenjihe.com"
custom_domain = true

[[routes]]
pattern = "www.bigroc.cn"
custom_domain = true